### ISSUE TITLE
Install without Admin Privileges

### ISSUE THREAD

**Issue by ghost** [nvim-neorocks/rocks-scoop#2]
Is it possible to change the instillation to not require admin privileges? Scoops main luarocks/lua packages can be installed as an unprivileged user.

**Comment by mrcjkb** [comment]
Hey 👋 

I've added a `/NOADMIN` flag. That should work if you don't need admin privileges to write to the install directory. 

The main luarocks scoop extracts a pre-built archive, this one builds luarocks from source. 

I don't have a Windows device I can test it on. Please let me know if it fails, in which case I will have to revert the change.

**Comment by ghost** [comment]
That was fast! As far as I can tell everything worked for installing without admin privileges.

Looks like I can't use rocks.nvim anyhow though because of needing permissions I don't have to make symlinks.

**Comment by mrcjkb** [comment]
> needing permissions I don't have to make symlinks.

What is the behaviour here? 
Does rocks.nvim fail to start or throw an error? 
In principle, it should be possible to use rocks.nvim without the symlinks it tries to create, but with reduced functionality (for example, tree-sitter parsers installed using luarocks won't work).

The only means we have for testing on Windows right now is a basic integration test on GitHub actions, so the experience might be a bit rocky at this point in time.

**Comment by ghost** [comment]
Looking at the error messages after getting some sleep the problem might not be symlinks, but I'm not sure what to do next.

I tried to follow the rocks.nvim's wiki article about windows setup. Here is my init.lua:

```lua
do
-- Specifies where to install/use rocks.nvim
local install_location = vim.fs.joinpath(vim.fn.stdpath("data"), "rocks")

-- Set up configuration options related to rocks.nvim (recommended to leave as default)
local rocks_config = {
rocks_path = vim.fs.normalize(install_location),
}

vim.g.rocks_nvim = rocks_config
print(rocks_config.rocks_path)

-- Configure the package path (so that plugin code can be found)
local luarocks_path = {
vim.fs.joinpath(rocks_config.rocks_path, "share", "lua", "5.1", "?.lua"),
vim.fs.joinpath(rocks_config.rocks_path, "share", "lua", "5.1", "?", "init.lua"),
}
package.path = package.path .. ";" .. table.concat(luarocks_path, ";")

-- Configure the C path (so that e.g. tree-sitter parsers can be found)
local luarocks_cpath = {
vim.fs.joinpath(rocks_config.rocks_path, "lib", "lua", "5.1", "?.so"),
vim.fs.joinpath(rocks_config.rocks_path, "lib64", "lua", "5.1", "?.so"),

vim.fs.joinpath(rocks_config.rocks_path, "lib", "lua", "5.1", "?.dll"),
vim.fs.joinpath(rocks_config.rocks_path, "lib64", "lua", "5.1", "?.dll"),
}
package.cpath = package.cpath .. ";" .. table.concat(luarocks_cpath, ";")

-- Load all installed plugins, including rocks.nvim itself
vim.opt.runtimepath:append(vim.fs.joinpath(rocks_config.rocks_path, "lib", "luarocks", "rocks-5.1", "rocks.nvim", "*"))
end
```

When I open Neovim or try to run `:Rocks install <something>` I get

(log):
```
[START][2024-08-15 10:42:40] rocks.nvim logging initiated
ERROR | 2024-08-15 10:42:40 | ...ta/Local/nvim-data/rocks/share/lua/5.1/rocks\adapter.lua:46 | Error creating symlink directory: lua (EPERM: operation not permitted: C:/Users/Tim.Bump/AppData/Local/nvim-data/rocks/share/lua/5.1 -> C:/Users/Tim.Bump/AppData/Local/nvim-data/rocks/rocks_rtp/lua)
E
ERROR | 2024-08-15 10:37:22 | ...a\Local\nvim-data\rocks\share\lua\5.1\rocks\luarocks.lua:65 | luarocks CLI FAILED
ERROR | 2024-08-15 10:37:22 | ...a\Local\nvim-data\rocks\share\lua\5.1\rocks\luarocks.lua:66 | Failed to invoke luarocks at luarocks: ...m-nightly\current\share\nvim\runtime/lua/vim/_system.lua:244: ENOENT: no such file or directory
```

(messages):
```
Error executing vim.schedule lua callback: ...ppData/Local/nvim-data/rocks/share/lua/5.1/nio\tasks.lua:100: Async task failed without callback: The coroutine failed with this message:
...Data/Local/nvim-data/rocks/share/lua/5.1/nio\control.lua:145: Failed to invoke luarocks at luarocks: ...m-nightly\current\share\nvim\runtime/lua/vim/_system.lua:244: ENOENT: no such file or directory
stack traceback:
        [C]: in function 'error'
        ...Data/Local/nvim-data/rocks/share/lua/5.1/nio\control.lua:145: in function 'wait'
        ...Data\Local\nvim-data\rocks\share\lua\5.1\rocks\state.lua:44: in function 'installed_rocks'
        ...ta/Local/nvim-data/rocks/share/lua/5.1/rocks\adapter.lua:150: in function 'init_site_symlinks_async'
        ...ta/Local/nvim-data/rocks/share/lua/5.1/rocks\adapter.lua:184: in function 'synchronise_site_symlinks'
        ...ta/Local/nvim-data/rocks/share/lua/5.1/rocks\adapter.lua:176: in function 'ensure_site_links'
        ...ta/Local/nvim-data/rocks/share/lua/5.1/rocks\adapter.lua:190: in function 'init'
        ...\luarocks\rocks-5.1\rocks.nvim\2.37.0-1\plugin\rocks.lua:57: in function <...\luarocks\rocks-5.1\rocks.nvim\2.37.0-1\plugin\rocks.lua:56>
stack traceback:
        [C]: in function 'error'
        ...ppData/Local/nvim-data/rocks/share/lua/5.1/nio\tasks.lua:100: in function 'close_task'
        ...ppData/Local/nvim-data/rocks/share/lua/5.1/nio\tasks.lua:122: in function 'cb'
        ...ppData/Local/nvim-data/rocks/share/lua/5.1/nio\tasks.lua:188: in function 'waiter'
        ...Data/Local/nvim-data/rocks/share/lua/5.1/nio\control.lua:116: in function 'wake'
        ...Data/Local/nvim-data/rocks/share/lua/5.1/nio\control.lua:137: in function 'set_error'
        ...Data\Local\nvim-data\rocks\share\lua\5.1\rocks\state.lua:38: in function 'on_exit'
        ...a\Local\nvim-data\rocks\share\lua\5.1\rocks\luarocks.lua:69: in function 'fn'
        vim/_editor.lua:351: in function <vim/_editor.lua:350>
```

For good measure here is my luarocks config file

```
fs_use_modules = false
lua_version = "5.1"
rocks_trees = {
	{
		name = "user",
		root = "C:\\Users\\<user>\\AppData\\Roaming/luarocks"
	},
	{
		name = "system",
		root = "C:/Users/<user>/scoop/apps/lua51/current\\systree"
	}
}
variables = {
	LUA_LIBDIR = "C:/Users/<user>/scoop/apps/lua51/current",
	MSVCRT = "MSVCR80",
        CC = "gcc",
	LD = "gcc",
}
verbose = false
```

I have gcc installed with scoop instead of mingw

**Comment by mrcjkb** [comment]
> Failed to invoke luarocks at luarocks: ...m-nightly\current\share\nvim\runtime/lua/vim/_system.lua:244: ENOENT: no such file or directory

`ENOENT: no such file or directory` is Neovim's user-friendly way of telling you that the command `luarocks` was not found.
It seems it's either not on the `PATH` or it's not visible to Neovim.

**Comment by ghost** [comment]
> `ENOENT: no such file or directory` is Neovim's user-friendly way of telling you that the command `luarocks` was not found. It seems it's either not on the `PATH` or it's not visible to Neovim.

I'm not sure why either would be the case. Scoop puts the path to the executable in my user's $PATH, and typing luarocks works in the terminal I'm using (Wezterm), and in the default terminal for both cmd and powershell. Is there a hardcoded path somewhere or could rocks be launching commands in some other shell that wouldn't inherit my environment?

**Comment by mrcjkb** [comment]
It's trying to invoke `luarocks`, according to the error message.
You can test it by running `:lua =vim.system({ "luarocks", "--version" }):wait()`

**Comment by ghost** [comment]
Oops, I had tried that before and it worked, but that was a different attempted installation. Now it fails. 

What's interesting is that if I do `:lua =vim.system({ "luarocks.bat", "--version" }):wait()` instead it works, but `luarocks` should just lead to the .bat file. as far as I can tell

<img width="811" alt="image" src="https://github.com/user-attachments/assets/7a3310ed-692f-409c-a22f-2ed89408b684">

**Comment by mrcjkb** [comment]
You could workaround that by setting `luarocks_binary = "luarocks.bat"` in your `rocks_config`.
I'll add a note to the wiki entry.

**Comment by ghost** [comment]
Looks like that works! Now I just need to figure out how to get rid of those annoying but not fatal `cannot open e  -e io.write(_VERSION:sub(5)) : No such file or directory` messages, but I won't bother you for that. Thank you!

**Comment by aaronedev** [comment]
@mrcjkb thank you for makin this i thought i was going crazy
